from .index import *
from .page import *
from .cathedras import *
from .cathedra import *
from .staff import *
from .admin import *
from .blocks import *
from .directions import *
from .schedule import *
from .push import *
from .news import *
from .announcements import *