# Generated by Django 3.2 on 2021-05-11 14:58

from django.db import migrations, models
import main.models.menu


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['order'], 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=main.models.menu.get_default_order, verbose_name='Порядок'),
        ),
    ]
