# Generated by Django 3.2 on 2021-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_menu_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kind',
            field=models.CharField(choices=[('default', '-'), ('group', 'Группа (без страницы)'), ('group_page', 'Группа (co страницей)'), ('page', 'Страница'), ('schedule', 'Расписание'), ('staff_list', 'Сотрудники'), ('staff_item', 'Сотрудник'), ('cathedra_list', 'Страница'), ('cathedra_item', 'Страница'), ('cathedra_page', 'Страница')], default='group', max_length=20, verbose_name='Тип'),
        ),
    ]
