# Generated by Django 3.2 on 2021-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210513_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='kind',
            field=models.CharField(choices=[('default', '-'), ('index', 'Главная'), ('group', 'Группа (без страницы)'), ('group_page', 'Группа (co страницей)'), ('page', 'Страница'), ('schedule', 'Расписание'), ('staff_list', 'Сотрудники'), ('staff_item', 'Сотрудник'), ('cathedra_list', 'Кафедры'), ('cathedra_item', 'Кафедра'), ('cathedra_page', 'Страница кафедры')], default='default', max_length=20, verbose_name='Тип'),
        ),
    ]
