# Generated by Django 3.2 on 2021-05-18 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210513_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kind',
            field=models.CharField(choices=[('default', '-'), ('index', 'Главная'), ('group', 'Группа (без страницы)'), ('group_page', 'Группа (co страницей)'), ('page', 'Страница'), ('document', 'Document'), ('schedule', 'Расписание'), ('staff_list', 'Сотрудники'), ('staff_item', 'Сотрудник'), ('cathedra_list', 'Кафедры'), ('cathedra_item', 'Кафедра'), ('cathedra_page', 'Страница кафедры')], default='default', max_length=20, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(max_length=200, verbose_name='Техническое имя')),
                ('object', models.FileField(upload_to='main/file_objects/', verbose_name='Файл')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
