# Generated by Django 3.2 on 2021-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210518_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='kind',
            field=models.CharField(choices=[('default', '-'), ('index', 'Главная'), ('group', 'Группа (без страницы)'), ('group_page', 'Группа (co страницей)'), ('page', 'Страница'), ('fileobject', 'Ссылка на файл'), ('schedule', 'Расписание'), ('staff_list', 'Сотрудники'), ('staff_item', 'Сотрудник'), ('cathedra_list', 'Кафедры'), ('cathedra_item', 'Кафедра'), ('cathedra_page', 'Страница кафедры')], default='default', max_length=20, verbose_name='Тип'),
        ),
    ]
