# Generated by Django 3.2 on 2021-05-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_menu_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(max_length=200, verbose_name='Техническое имя')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Внутренняя ссылка',
                'verbose_name_plural': 'Внутренние ссылки',
            },
        ),
    ]
