# Generated by Django 3.2 on 2021-05-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_innerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(max_length=200, verbose_name='Техническое имя')),
                ('html', models.TextField(verbose_name='HTML')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='main/images/cathedras/icons', verbose_name='Иконка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/images/cathedras/images', verbose_name='Картинка')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
    ]
