# Generated by Django 3.2 on 2021-05-19 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_cathedra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cathedra',
            name='menu',
        ),
    ]
