# Generated by Django 3.2 on 2021-05-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_cathedra_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('category', models.CharField(choices=[('staff', 'Штатный'), ('leader', 'Руководитель')], default='staff', max_length=20, verbose_name='Категория')),
                ('html', models.TextField(verbose_name='HTML')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/images/staff/images', verbose_name='Картинка')),
                ('cathedra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='main.cathedra', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
