# Generated by Django 3.2 on 2021-05-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_direction_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
    ]
