# Generated by Django 3.2 on 2021-05-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_direction_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='degree',
            field=models.CharField(choices=[('magistracy', 'Магистратура'), ('baccalaureate', 'Бакалавриат'), ('postgraduate', 'Аспирантура')], default='magistracy', max_length=20, verbose_name='Степень'),
        ),
    ]
