# Generated by Django 3.2 on 2021-05-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_direction_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sidebar_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Название подменю'),
        ),
    ]
