# Generated by Django 3.2 on 2021-05-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_page_sidebar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_sidebar',
            field=models.BooleanField(default=False, verbose_name='Подменю?'),
        ),
    ]
