# Generated by Django 3.2 on 2021-05-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_page_is_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='main.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_sidebar',
            field=models.BooleanField(default=False, verbose_name='Сайдбар?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sidebar_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Сайдбар, название'),
        ),
    ]
