# Generated by Django 3.2 on 2021-05-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210521_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Отображается?'),
        ),
    ]
