# Generated by Django 3.2 on 2021-05-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_pageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='slug',
            field=models.CharField(default='', max_length=200, verbose_name='Техническое имя'),
            preserve_default=False,
        ),
    ]
