# Generated by Django 3.2 on 2021-05-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_pageimage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Учебный день',
                'verbose_name_plural': 'Учебные дни',
            },
        ),
        migrations.CreateModel(
            name='ScheduleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.CharField(max_length=200, verbose_name='Техническое имя')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Важное сообщение')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Время начала - время конца')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scheduleday', verbose_name='Учебный день')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
            },
        ),
        migrations.CreateModel(
            name='SchedulePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Время начала - время конца')),
                ('appearance', models.CharField(choices=[('always', 'Всегда'), ('numerator', 'Числитель'), ('denominator', 'Знаменатель')], default='always', max_length=20, verbose_name='Числитель/знаменатель')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.scheduletimeslot', verbose_name='Временной слот')),
            ],
            options={
                'verbose_name': 'Пара',
                'verbose_name_plural': 'Пары',
            },
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedulegroup', verbose_name='Группа'),
        ),
    ]
