# Generated by Django 3.2 on 2021-05-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210521_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleday',
            options={'ordering': ['number'], 'verbose_name': 'Учебный день', 'verbose_name_plural': 'Учебные дни'},
        ),
        migrations.AlterModelOptions(
            name='schedulegroup',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='scheduletimeslot',
            options={'ordering': ['number'], 'verbose_name': 'Временной слот', 'verbose_name_plural': 'Временные слоты'},
        ),
        migrations.RenameField(
            model_name='scheduletimeslot',
            old_name='name',
            new_name='time',
        ),
        migrations.AddField(
            model_name='scheduleday',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduletimeslot',
            name='appearance',
            field=models.CharField(choices=[('always', 'Всегда'), ('numerator', 'Числитель'), ('denominator', 'Знаменатель')], default='always', max_length=20, verbose_name='Числитель/знаменатель'),
        ),
        migrations.AddField(
            model_name='scheduletimeslot',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduletimeslot',
            name='pair',
            field=models.CharField(default='', max_length=200, verbose_name='Пара'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SchedulePair',
        ),
    ]
