# Generated by Django 3.2 on 2021-05-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210522_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduletimeslot',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='scheduletimeslot',
            name='pair',
        ),
        migrations.AddField(
            model_name='scheduletimeslot',
            name='is_whole',
            field=models.BooleanField(default=True, verbose_name='Целый слот?'),
        ),
        migrations.AddField(
            model_name='scheduletimeslot',
            name='pair_denominator',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Пара (знаменатель)'),
        ),
        migrations.AddField(
            model_name='scheduletimeslot',
            name='pair_numerator',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Пара (числитель)'),
        ),
    ]
