# Generated by Django 3.2 on 2021-05-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210524_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleday',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='main.schedulegroup', verbose_name='Группа'),
        ),
    ]
