# Generated by Django 3.2 on 2021-05-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_scheduleday_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletimeslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='main.scheduleday', verbose_name='Учебный день'),
        ),
    ]
