# Generated by Django 3.2 on 2021-05-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_scheduletimeslot_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=200, verbose_name='Техническое имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main/images/news/images', verbose_name='Картинка')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Описание')),
                ('html', models.TextField(verbose_name='HTML')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('is_slider', models.BooleanField(default=False, verbose_name='Слайдер?')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
