# Generated by Django 3.2 on 2021-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/images/announcement/images', verbose_name='Картинка'),
        ),
    ]
