# Generated by Django 3.2 on 2021-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='category',
            field=models.CharField(choices=[('staff', 'Штатный'), ('leader', 'Руководитель'), ('deanery', 'Деканат'), ('council', 'Учёный совет')], default='staff', max_length=20, verbose_name='Категория'),
        ),
    ]
