from .setting import *
from .menu import *
from .page import *
from .file_object import *
from .cathedra import *
from .inner_link import *
from .staff import *
from .direction import *
from .schedule import *